### ISSUE TITLE
Error: Cannot find transform for node Node<"heading">

### ISSUE THREAD

**Issue by MonicaRungi-w** [octet-stream/slate-to-react#9]
"heading" is not recognized: 
<img width="425" alt="Screenshot 2024-05-06 alle 11 47 09" src="https://github.com/octet-stream/slate-to-react/assets/84009241/1efd2bab-b01a-43b2-808a-a605521a811c">

"isHeading" function isn't checking the node type "heading":
<img width="512" alt="Screenshot 2024-05-06 alle 11 48 38" src="https://github.com/octet-stream/slate-to-react/assets/84009241/bb4e6ec7-74f0-4946-a9dd-8dbcee370fad">

**Comment by octet-stream** [comment]
Hello. Thanks for your feedback!
Every transform in `slate-to-react` matches the type `type` against corresponding html tag, so in order for it to work, your node must have the `h<level>` type. Because Slate does not enforce any specific schema rules, other than `children` field for elements and `text` for leaves, I simply cannot cover every possible scenario for matchers. This is what [`createElementTransform`](https://github.com/octet-stream/slate-to-react#createelementtransformmatcher-transform), [`createLeafTransform`](https://github.com/octet-stream/slate-to-react#createleaftransformmatcher-transform), [`createElementNodeMatcher`](https://github.com/octet-stream/slate-to-react#createelementnodematchermatcher) and [`createLeafNodeMatcher`](https://github.com/octet-stream/slate-to-react#createleafnodematchermatcher) are for, so you can bring your own components to render Slate nodes the way that fits your own needs.

This is how you can create your custom element element matcher & transform:

```ts
import {createElement} from "react"
import {createElementNodeMatcher} from "slate-to-react"

export interface Heading {
  type: "heading"
  level: 1 | 2 | 3 | 4 | 5 | 6
  children: InlineDescendant[] // This would be your own type
}

export const isHeading = createElementNodeMatcher<Heading>((node): node is Heading => (
  node.type === "heading"
    && typeof node.level === "number"
    && node.level >= 1
    && node.level <= 6
))

export const HeadingElement = createElementTransform(
  isHeading,

  ({key, attributes, element, children}) => createElement(
    element.level,

    {
      ...attributes,

      key
    }
  )
)
```

I also recommend disabling all default transforms so you can see where you need to add custom elements by setting the `defaultTransforms` option to `false`. See: https://github.com/octet-stream/slate-to-react#type-transformnodesoptions

To be clear, this is the convention taken from [Plate's](https://platejs.org/) schema – they typically place tag names in the `type` field and this is why I made it in my package by default.

**Comment by MonicaRungi-w** [comment]
@octet-stream Thank you for the quick response! :)

**Comment by octet-stream** [comment]
I'm closing this. Hope your issue is resolved. Feel free to reopen if not.
